[build-system]
requires = [
  "setuptools >= 41.2.0",
  "setuptools_scm >= 1.15.0",
  "setuptools_scm_git_archive >= 1.0",
  "wheel",

  # hack:
  "beautifulsoup4",
  "requests",
]
build-backend = "setuptools.build_meta"
